[package]
name = "tic-tac-toe"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "tic-tac-toe"
path = "src/main.rs"


[dependencies]
gtk = "0.9.2"